name: CI
on:
  push:
    branches:
    - master
  # rebuild images every night
  schedule:
  - cron: 0 3 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
        - pulse-secure-client
        - openssh-proxy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Login
      run: docker login --username dadevel --password-stdin <<< $DOCKERHUB_TOKEN
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image
      run: docker build --tag dadevel/${{ matrix.image }}:latest ./${{ matrix.image }}
    - name: Push image
      run: docker push dadevel/${{ matrix.image }}:latest
    - name: Logout
      run: docker logout

